version: "3.3"

services:
  flexlm:
    image: kdfischer/docker-comsolflexlmserver
    hostname: flexlm.example.com
    mac_address: ba:98:76:54:32:10
    volumes:
      - ./distrib/license.dat:/usr/local/flexlm/licenses/license.dat:ro
    ports:
      - 7018
      - 7019
    secrets:
      - comsol_license_5.3a
    deploy:
      mode: replicated
      replicas: 1

secrets:
  comsol_license_5.3a:
    external: true